force-app/main/default/objects/Customer__c/Customer__c.object-meta.xml
<CustomObject>
    <label>Customer</label>
    <nameField>
        <displayFormat>CNum-{0}</displayFormat>
        <label>Customer Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Customers</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Customer__c/fields/Cashier__c.field-meta.xml
<CustomField>
    <fullName>Cashier__c</fullName>
    <label>Cashier</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Customers</relationshipLabel>
    <relationshipName>Customers</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Customer__c/fields/Is_Served__c.field-meta.xml
<CustomField>
    <fullName>Is_Served__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Is Served</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Customer__c/fields/subtotal__c.field-meta.xml
<CustomField>
    <fullName>subtotal__c</fullName>
    <label>subtotal</label>
    <precision>5</precision>
    <required>true</required>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Customer__c/fields/tip__c.field-meta.xml
<CustomField>
    <fullName>tip__c</fullName>
    <label>tip</label>
    <precision>5</precision>
    <scale>3</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/classes/CustomerServedController.cls
public class CustomerServedController{
    public List<Customer__c> csServed {get;set;}
    public CustomerServedController(){
        csServed = new List<Customer__c>();
    }
    public void addServed(){
        for(Customer__c c: [select Cashier__c, subtotal__c, tip__c, is_Served__c from Customer__c]){
            if(c.is_Served__c){
                csServed.add(c);
            }
        }
    }
}