force-app/main/default/objects/Customer__c/Customer__c.object-meta.xml
<CustomObject>
    <label>Customer</label>
    <nameField>
        <displayFormat>CNum-{0}</displayFormat>
        <label>Customer Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Customers</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Customer__c/fields/Cashier__c.field-meta.xml
<CustomField>
    <fullName>Cashier__c</fullName>
    <label>Cashier</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Customers</relationshipLabel>
    <relationshipName>Customers</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Customer__c/fields/subtotal__c.field-meta.xml
<CustomField>
    <fullName>subtotal__c</fullName>
    <label>subtotal</label>
    <precision>5</precision>
    <required>true</required>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Customer__c/fields/tip__c.field-meta.xml
<CustomField>
    <fullName>tip__c</fullName>
    <label>tip</label>
    <precision>5</precision>
    <scale>3</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/classes/CustomerSelect.cls
public class CustomerSelect{
   public List<Customer__c> customers15{get;set;}
   public List<Customer__c> customers10{get;set;}
   public List<Customer__c> customers5{get;set;}
    public CustomerSelect(){
        customers15=new List<Customer__c>();
        customers10=new List<Customer__c>();
        customers5=new List<Customer__c>();
    }
    public void addTip(){
        for(Customer__c c:[select Cashier__c, subtotal__c, tip__c from Customer__c]){
            if(c.tip__c>=c.subtotal__c*0.15){customers15.add(c);}
            else if(c.tip__c>=c.subtotal__c*0.10){customers10.add(c);}
            else{customers5.add(c);}
        }
    }
}