force-app/main/default/objects/Customer__c/Customer__c.object-meta.xml
<CustomObject>
    <label>Customer</label>
    <nameField>
        <displayFormat>CNum-{0}</displayFormat>
        <label>Customer Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Customers</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Customer__c/fields/Cashier__c.field-meta.xml
<CustomField>
    <fullName>Cashier__c</fullName>
    <label>Cashier</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Customers</relationshipLabel>
    <relationshipName>Customers</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Customer__c/fields/Is_Served__c.field-meta.xml
<CustomField>
    <fullName>Is_Served__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Is Served</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Customer__c/fields/subtotal__c.field-meta.xml
<CustomField>
    <fullName>subtotal__c</fullName>
    <label>subtotal</label>
    <precision>5</precision>
    <required>true</required>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Customer__c/fields/tip__c.field-meta.xml
<CustomField>
    <fullName>tip__c</fullName>
    <label>tip</label>
    <precision>5</precision>
    <scale>3</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/classes/CustomerUpdate.cls
public class CustomerUpdate implements Database.Batchable<sObject>{
    public List<customer__c>cusList {get;set;}
    public CustomerUpdate (){
        cusList = new List<customer__c>();
    }
    public Database.QueryLocator start(Database.BatchableContext bc){
        
        return Database.getQueryLocator('select Name, Cashier__c, subtotal__c, tip__c, is_Served__c, Service_status__c from customer__c');
    }
    public void execute(Database.BatchableContext bc, List<customer__c>clist){
        for(customer__c c:clist){
            if(c.Is_Served__c==True)
            {c.Service_status__c='IS SERVED';}
            else{c.Service_status__c='NOT SERVED YET';}
        }
        update clist;
    }
    public void finish(Database.BatchableContext bc){}
}