force-app/main/default/objects/Customer__c/Customer__c.object-meta.xml
<CustomObject>
    <label>Customer</label>
    <nameField>
        <displayFormat>CNum-{0}</displayFormat>
        <label>Customer Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Customers</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Customer__c/fields/Cashier__c.field-meta.xml
<CustomField>
    <fullName>Cashier__c</fullName>
    <label>Cashier</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Customers</relationshipLabel>
    <relationshipName>Customers</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Customer__c/fields/subtotal__c.field-meta.xml
<CustomField>
    <fullName>subtotal__c</fullName>
    <label>subtotal</label>
    <precision>5</precision>
    <required>true</required>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Franchise__c/Franchise__c.object-meta.xml
<CustomObject>
    <label>Franchise</label>
    <nameField>
        <displayFormat>Franchise-{0}</displayFormat>
        <label>Franchise</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Franchises</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

force-app/main/default/objects/Franchise__c/fields/Franchise_Country__c.field-meta.xml
<CustomField>
    <fullName>Franchise_Country__c</fullName>
    <label>Franchise Country</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Italy</fullName>
            </value>
            <value>
                <fullName>United States</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Franchise__c/fields/Franchise_Name__c.field-meta.xml
<CustomField>
    <fullName>Franchise_Name__c</fullName>
    <label>Franchise Name</label>
    <length>70</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Worker__c/Worker__c.object-meta.xml
<CustomObject>
    <label>Worker</label>
    <nameField>
        <displayFormat>Worker-{0}</displayFormat>
        <label>Worker Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Workers</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Worker__c/fields/email__c.field-meta.xml
<CustomField>
    <fullName>email__c</fullName>
    <description>Enter your worker email address</description>
    <label>email</label>
    <length>32</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Worker__c/fields/Firstname__c.field-meta.xml
<CustomField>
    <fullName>Firstname__c</fullName>
    <label>Firstname</label>
    <length>24</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Worker__c/fields/Lastname__c.field-meta.xml
<CustomField>
    <fullName>Lastname__c</fullName>
    <label>Lastname</label>
    <length>24</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Worker__c/fields/twoweeksnotice__c.field-meta.xml
<CustomField>
    <fullName>twoweeksnotice__c</fullName>
    <label>twoweeksnotice</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>twoweeksnotice</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Worker_Schedule__c/Worker_Schedule__c.object-meta.xml
<CustomObject>
    <label>Worker Schedule</label>
    <nameField>
        <displayFormat>WS-{0}</displayFormat>
        <label>Work Schedule</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Worker Schedules</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Worker_Schedule__c/fields/DayWorked__c.field-meta.xml
<CustomField>
    <fullName>DayWorked__c</fullName>
    <label>DayWorked</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Worker_Schedule__c/fields/Franchise__c.field-meta.xml
<CustomField>
    <fullName>franchise__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>franchise</label>
    <referenceTo>franchise__c</referenceTo>
    <relationshipLabel>worker schedules</relationshipLabel>
    <relationshipName>worker_schedules</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Worker_Schedule__c/fields/HoursWorked__c.field-meta.xml
<CustomField>
    <fullName>HoursWorked__c</fullName>
    <label>HoursWorked</label>
    <length>2</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Worker_Schedule__c/fields/Worker__c.field-meta.xml
<CustomField>
    <fullName>Worker__c</fullName>
    <label>Worker</label>
    <referenceTo>Worker__c</referenceTo>
    <relationshipLabel>Worker Schedules</relationshipLabel>
    <relationshipName>Worker_Schedules</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/classes/TriggerTest.cls
@isTest
public class TriggerTest {
    @isTest
    public static void testFranchiseDelete(){
 	Franchise__c franc=new Franchise__c(Franchise_Country__c='United States',Franchise_Name__c='Franchise - ' + Math.random());
    insert franc;
    delete franc;
    }
 /*   @isTest 
    public static void testWorkerDelete(){
        Worker__c work=new Worker__c(Firstname__c='jimbob',Lastname__c='boblerk',Email__c='jimbobboblerk@geek.test',twoweeksnotice__c='yes');
     	insert work;
 		//System.assert(work.twoweeksnotice__c);
        delete work;
        }*/
              
    
/*@isTest
public static void testWorkerScheduleUpdate(){
    Worker_Schedule__c wS=new Worker_Schedule__c(DayWorked__c=Date.parse('7/12/2021'),HoursWorked__c='2');
    Date testDate=Date.parse('7/11/2021');
    wS.DayWorked__c=testDate;
    update wS;
    wS.DayWorked__c=null;
    update wS;
   // wS.DayWorked__c=null;
    //wS.DayWorked__c=Date.parse('07/14/2021');
   
}*/
    @isTest
    public static void testCustomerInsert(){
        Worker__c work=new Worker__c(Firstname__c='jimbob',Lastname__c='boblerk',Email__c='jimbobboblerk@geek.test',twoweeksnotice__c='yes');
        insert work;
        Customer__c c=new Customer__c(Cashier__c=work.Id,subtotal__c=20.00);
        
        insert c;
        
        
    }
}