force-app/main/default/objects/Customer__c/Customer__c.object-meta.xml
<CustomObject>
    <label>Customer</label>
    <nameField>
        <displayFormat>CNum-{0}</displayFormat>
        <label>Customer Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Customers</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Customer__c/fields/Cashier__c.field-meta.xml
<CustomField>
    <fullName>Cashier__c</fullName>
    <label>Cashier</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Customers</relationshipLabel>
    <relationshipName>Customers</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Customer__c/fields/Is_Served__c.field-meta.xml
<CustomField>
    <fullName>Is_Served__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Is Served</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Customer__c/fields/subtotal__c.field-meta.xml
<CustomField>
    <fullName>subtotal__c</fullName>
    <label>subtotal</label>
    <precision>5</precision>
    <required>true</required>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Customer__c/fields/tip__c.field-meta.xml
<CustomField>
    <fullName>tip__c</fullName>
    <label>tip</label>
    <precision>5</precision>
    <scale>3</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/classes/CustomerUpdateTest.cls
@isTest
private with sharing class CustomerUpdateTest {
    
    public static testmethod void test(){
        List<customer__c>cList = new List<customer__c>();
        for(integer i=0; i<200;i++){
            customer__c c = new customer__c();
            c.Is_Served__c=true;
            c.Service_status__c='NOT SERVED YET';
            cList.add(c);
        }
        insert cList;

        Test.startTest();
        CustomerUpdate cu = new CustomerUpdate();
        Database.executeBatch(cu);
        Test.stopTest();
        List<customer__c>customerList = [select Name, Cashier__c, subtotal__c, tip__c, is_Served__c, Service_status__c from customer__c]; 
        system.assertEquals(customerList[0].Service_Status__c, 'IS SERVED');
       
    }
}