force-app/main/default/objects/Franchise__c/Franchise__c.object-meta.xml
<CustomObject>
    <label>Franchise</label>
    <nameField>
        <displayFormat>Franchise-{0}</displayFormat>
        <label>Franchise</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Franchises</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

force-app/main/default/objects/Worker__c/Worker__c.object-meta.xml
<CustomObject>
    <label>Worker</label>
    <nameField>
        <displayFormat>Worker-{0}</displayFormat>
        <label>Worker Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Workers</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Worker_Schedule__c/Worker_Schedule__c.object-meta.xml
<CustomObject>
    <label>Worker Schedule</label>
    <nameField>
        <displayFormat>WS-{0}</displayFormat>
        <label>Work Schedule</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Worker Schedules</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Worker_Schedule__c/fields/DayWorked__c.field-meta.xml
<CustomField>
    <fullName>DayWorked__c</fullName>
    <label>DayWorked</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Worker_Schedule__c/fields/Franchise__c.field-meta.xml
<CustomField>
    <fullName>franchise__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>franchise</label>
    <referenceTo>franchise__c</referenceTo>
    <relationshipLabel>worker schedules</relationshipLabel>
    <relationshipName>worker_schedules</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Worker_Schedule__c/fields/Worker__c.field-meta.xml
<CustomField>
    <fullName>Worker__c</fullName>
    <label>Worker</label>
    <referenceTo>Worker__c</referenceTo>
    <relationshipLabel>Worker Schedules</relationshipLabel>
    <relationshipName>Worker_Schedules</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/classes/FranchiseEmployeeControllerTest.cls
@isTest
private class FranchiseEmployeeControllerTest { 
    
    @isTest
    public static void emptyWorkerTest(){
        FranchiseEmployeeController controllerTest = new FranchiseEmployeeController();
        System.assertNotEquals(controllerTest.dat, Date.today());
        controllerTest.dat = Date.today();
        controllerTest.getWorkers();
        System.assertEquals(controllerTest.dat, Date.today());
        System.assertEquals(controllerTest.franchiseStore.isEmpty(), controllerTest.franchiseStore.Size() == 0);
    }
    
    @isTest
    public static void getWorkersTest(){
        FranchiseEmployeeController controllerTest = new FranchiseEmployeeController();
        worker_schedule__c testWorkerA = new worker_schedule__c(name='testWorkerA',worker__c='Willy',
                                                               franchise__c='Wonk',dayworked__c = Date.today());
        worker_schedule__c testWorkerB = new worker_schedule__c(name='testWorkerA',worker__c='Billy',
                                                               franchise__c='Goat',dayworked__c = Date.newInstance(1995, 12, 25));
        System.assertNotEquals(controllerTest.dat, Date.today());
        controllerTest.dat = Date.today();
        System.assertEquals(controllerTest.dat, Date.today());
        insert testWorkerA;
        insert testWorkerB;
        System.assert(controllerTest.franchiseStore.isEmpty());
        controllerTest.getWorkers();
        System.assertNotEquals(controllerTest.franchiseStore.isEmpty(), controllerTest.franchiseStore.Size() == 0);
    }
}