force-app/main/default/objects/Franchise__c/Franchise__c.object-meta.xml
<CustomObject>
    <label>Franchise</label>
    <nameField>
        <displayFormat>Franchise-{0}</displayFormat>
        <label>Franchise</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Franchises</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

force-app/main/default/objects/Worker__c/Worker__c.object-meta.xml
<CustomObject>
    <label>Worker</label>
    <nameField>
        <displayFormat>Worker-{0}</displayFormat>
        <label>Worker Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Workers</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Worker_Schedule__c/Worker_Schedule__c.object-meta.xml
<CustomObject>
    <label>Worker Schedule</label>
    <nameField>
        <displayFormat>WS-{0}</displayFormat>
        <label>Work Schedule</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Worker Schedules</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Worker_Schedule__c/fields/DayWorked__c.field-meta.xml
<CustomField>
    <fullName>DayWorked__c</fullName>
    <label>DayWorked</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Worker_Schedule__c/fields/Franchise__c.field-meta.xml
<CustomField>
    <fullName>franchise__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>franchise</label>
    <referenceTo>franchise__c</referenceTo>
    <relationshipLabel>worker schedules</relationshipLabel>
    <relationshipName>worker_schedules</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Worker_Schedule__c/fields/Worker__c.field-meta.xml
<CustomField>
    <fullName>Worker__c</fullName>
    <label>Worker</label>
    <referenceTo>Worker__c</referenceTo>
    <relationshipLabel>Worker Schedules</relationshipLabel>
    <relationshipName>Worker_Schedules</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/classes/FranchiseEmployeeController.cls
public class FranchiseEmployeeController {
	public Date dat {get;set;}
    public Set<worker_schedule__c>workSet{get;set;}
    public List<worker_schedule__c> franchiseStore {get;set;}
    public FranchiseEmployeeController() {
        workSet = new Set<worker_schedule__c>();
		franchiseStore = new List<worker_schedule__c>();
    }
    public void getWorkers(){
        franchiseStore.clear();
        for(worker_schedule__c work: [SELECT Name, worker__c, franchise__c, dayworked__c FROM worker_schedule__c]){
            if(work.dayworked__c == dat){
               workSet.add(work);
            }
        }
        franchiseStore.addAll(workSet);
    }
}